name: Typescript

on:
  push:

jobs:
  build:
      name: Typescript Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: PHPCS check
          uses: alexthemaster/action-build-typescript@v1.2.1
