name: Typescript

on:
  push:

jobs:
  build:
      name: Typescript
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Typescript Build
          uses: alexthemaster/action-build-typescript@v1.2.1
